# Generated by Django 5.2.8 on 2025-12-08 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_apivideocomment_apivideoview_apivideofavorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('eporner', 'Eporner'), ('redtube', 'RedTube'), ('hentai', 'Hentai')], default='eporner', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('watching', 'Currently Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], default='plan_to_watch', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('times_watched', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video_id', 'source')},
            },
        ),
    ]
