# Generated by Django 5.2.8 on 2025-12-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='list_is_public',
            field=models.BooleanField(default=True, help_text='Allow others to see your video list'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_favorites',
            field=models.BooleanField(default=False, help_text='Show favorites on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_stats',
            field=models.BooleanField(default=True, help_text='Show list statistics on public profile'),
        ),
    ]
